# Generated by Django 5.0.4 on 2024-04-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/$Y/$m/$d/')),
                ('lastname_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('facebook_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('g_plus_link', models.URLField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
