# Generated by Django 5.0.4 on 2024-04-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lastname_name',
            new_name='last_name',
        ),
    ]
