# Generated by Django 5.0.4 on 2024-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_lastname_name_member_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
