"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-07794u6ju=wjnvf5)fd5qg7e4=z6i(fros8g$mz0*#d*py5_i^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts.apps.AccountsConfig',
    'pages.apps.PagesConfig',
    'cars.apps.CarsConfig',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'HOST': localhost',
    #     'NAME': carzone',
    #     'USER': postgres',
    #     'PASSWORD': password',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-ub'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CK Editor 5 settings
# https://ckeditor.com

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload',
        ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': [
            'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
            'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
            'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
            'insertTable',
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|', 'imageStyle:alignLeft',
                'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': [
                    {
                        'color': 'hsl(4, 90%, 58%)',
                        'label': 'Red'
                    },
                    {
                        'color': 'hsl(340, 82%, 52%)',
                        'label': 'Pink'
                    },
                    {
                        'color': 'hsl(291, 64%, 42%)',
                        'label': 'Purple'
                    },
                    {
                        'color': 'hsl(262, 52%, 47%)',
                        'label': 'Deep Purple'
                    },
                    {
                        'color': 'hsl(231, 48%, 48%)',
                        'label': 'Indigo'
                    },
                    {
                        'color': 'hsl(207, 90%, 54%)',
                        'label': 'Blue'
                    },
                ],
                'backgroundColors': [
                    {
                        'color': 'hsl(4, 90%, 58%)',
                        'label': 'Red'
                    },
                    {
                        'color': 'hsl(340, 82%, 52%)',
                        'label': 'Pink'
                    },
                    {
                        'color': 'hsl(291, 64%, 42%)',
                        'label': 'Purple'
                    },
                    {
                        'color': 'hsl(262, 52%, 47%)',
                        'label': 'Deep Purple'
                    },
                    {
                        'color': 'hsl(231, 48%, 48%)',
                        'label': 'Indigo'
                    },
                    {
                        'color': 'hsl(207, 90%, 54%)',
                        'label': 'Blue'
                    },
                ]
            },
            'tableCellProperties': {
                'borderColors': [
                    {
                        'color': 'hsl(4, 90%, 58%)',
                        'label': 'Red'
                    },
                    {
                        'color': 'hsl(340, 82%, 52%)',
                        'label': 'Pink'
                    },
                    {
                        'color': 'hsl(291, 64%, 42%)',
                        'label': 'Purple'
                    },
                    {
                        'color': 'hsl(262, 52%, 47%)',
                        'label': 'Deep Purple'
                    },
                    {
                        'color': 'hsl(231, 48%, 48%)',
                        'label': 'Indigo'
                    },
                    {
                        'color': 'hsl(207, 90%, 54%)',
                        'label': 'Blue'
                    },
                ],
                'backgroundColors': [
                    {
                        'color': 'hsl(4, 90%, 58%)',
                        'label': 'Red'
                    },
                    {
                        'color': 'hsl(340, 82%, 52%)',
                        'label': 'Pink'
                    },
                    {
                        'color': 'hsl(291, 64%, 42%)',
                        'label': 'Purple'
                    },
                    {
                        'color': 'hsl(262, 52%, 47%)',
                        'label': 'Deep Purple'
                    },
                    {
                        'color': 'hsl(231, 48%, 48%)',
                        'label': 'Indigo'
                    },
                    {
                        'color': 'hsl(207, 90%, 54%)',
                        'label': 'Blue'
                    },
                ]
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
