# Generated by Django 5.0.4 on 2024-04-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_description_alter_car_doors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
        migrations.AddField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='airbags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='alarm_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='audio_interface',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='bluetooth_handset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='cruise_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='direct_fuel_injection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='park_assist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='power_steering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='reversing_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='seat_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='wind_deflector',
            field=models.BooleanField(default=False),
        ),
    ]
