# Generated by Django 5.0.4 on 2024-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_features_car_air_conditioning_car_airbags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=4),
        ),
    ]
